# Generated by Django 3.0.3 on 2020-08-19 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200819_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employee',
            name='hire_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='employee',
            name='comment',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
