# Generated by Django 3.0.3 on 2020-08-21 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('avatar', models.ImageField(upload_to='app')),
            ],
        ),
        migrations.AlterField(
            model_name='area',
            name='title',
            field=models.CharField(max_length=30, verbose_name='地名'),
        ),
    ]
